Repository SemanticMediaWiki/SemanticMediaWiki, pull requests merged in 2018-09, with the labels that each got.

#3375 Special:Search Avoid "Invalid sort: title. Must be one of: relevance"
  src/MediaWiki/Search/Search.php
Labels: mediawiki

#3382 Removes shell script for providing file releases
  build/release/build_tarballs.sh
  docs/RELEASE-NOTES.md
Labels: releasenotes

#3381 Add API `psubject` smwbrowse module
  DefaultSettings.php
  res/Resources.php
  res/smw/util/ext.smw.util.autocomplete.propertysubject.js
  src/MediaWiki/Api/Browse.php
  src/MediaWiki/Api/Browse/PSubjectLookup.php
  tests/phpunit/Integration/JSONScript/Fixtures/res.a-0001.10.txt
  tests/phpunit/Integration/JSONScript/Fixtures/res.a-0001.11.txt
  tests/phpunit/Integration/JSONScript/Fixtures/res.a-0001.9.txt
  tests/phpunit/Integration/JSONScript/TestCases/a-0001.json
  tests/phpunit/Unit/MediaWiki/Api/Browse/PSubjectLookupTest.php
  tests/phpunit/Unit/MediaWiki/Api/BrowseTest.php
Labels: feature, wikidocu missing

#3385 Add PropertyTableUpdater
  includes/storage/SQLStore/SMW_SQLStore3_Writers.php
  src/Parameters.php
  src/SQLStore/Exception/TableMissingIdFieldException.php
  src/SQLStore/PropertyTableUpdater.php
  src/SQLStore/SQLStoreFactory.php
  tests/phpunit/Unit/ParametersTest.php
  tests/phpunit/Unit/SQLStore/Exception/TableMissingIdFieldExceptionTest.php
  tests/phpunit/Unit/SQLStore/PropertyTableUpdaterTest.php
  tests/phpunit/includes/SQLStore/Writer/ChangeTitleTest.php
  tests/phpunit/includes/SQLStore/Writer/DataUpdateTest.php
  tests/phpunit/includes/SQLStore/Writer/DeleteSubjectTest.php
Labels: code quality

#3390 [DB] Add `smw_rev` field to track associated revision
  DefaultSettings.php
  includes/storage/SQLStore/SMW_SQLStore3_Writers.php
  includes/storage/SQLStore/SMW_Sql3SmwIds.php
  src/DataUpdater.php
  src/Elastic/ElasticStore.php
  src/SQLStore/TableFieldUpdater.php
  src/SQLStore/TableSchemaManager.php
  tests/phpunit/Unit/SQLStore/TableFieldUpdaterTest.php
Labels: feature

#3393 MW 1.31+ Highlighter avoid <div> in <span> (causes an extra inline <p> element)
  includes/Highlighter.php
  res/smw/util/ext.smw.util.tooltip.css
  tests/phpunit/Integration/JSONScript/Fixtures/res.a-0001.8.txt
  tests/phpunit/Integration/JSONScript/TestCases/f-0105.json
  tests/phpunit/Integration/JSONScript/TestCases/f-0204.json
  tests/phpunit/Integration/JSONScript/TestCases/f-0206.json
  tests/phpunit/Integration/JSONScript/TestCases/f-0209.json
  tests/phpunit/Integration/JSONScript/TestCases/f-0210.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0106.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0108.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0110.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0212.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0415.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0425.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0436.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0438.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0703.json
  tests/phpunit/Integration/JSONScript/TestCases/s-0011.json
  tests/phpunit/Unit/DataValues/InfoLinksProviderTest.php
  tests/phpunit/Unit/DataValues/ValueFormatters/NumberValueFormatterTest.php
  tests/phpunit/Unit/DataValues/ValueFormatters/PropertyValueFormatterTest.php
Labels: mediawiki

#3416 Property page add <section> support, refs 3308
  i18n/en.json
  res/smw/ext.smw.page.css
  src/MediaWiki/Hooks/HookListener.php
  src/Page/PropertyPage.php
  src/ParserFunctions/SectionTag.php
  tests/phpunit/Unit/ParserFunctions/SectionTagTest.php
Labels: feature, wikidocu missing

#3399 Remove functions deprecated since 1.9 from DataValueFactory
  src/DataValueFactory.php
  tests/phpunit/Unit/DataValueFactoryTest.php
Labels: code quality

#3400 Update deprecation notice
  includes/datavalues/SMW_DataValue.php
Labels: code quality

#3401 Remove long deprecated methods
  src/Query/ResultPrinters/ResultPrinter.php
Labels: code quality

#3403 Remove long deprecated getNextObject
  includes/storage/SMW_ResultArray.php
Labels: code quality

#3404 Remove long deprecated SMWJsonResultPrinter class alias
  includes/queryprinters/JsonResultPrinter.php
Labels: code quality

#3405 Remove long deprecated SMWDIString
  includes/dataitems/SMW_DI_String.php
Labels: code quality

#3406 Remove long deprecated getDVs function
  includes/datavalues/SMW_DV_Record.php
Labels: code quality

#3407 Remove smwfIsSemanticsProcessed deprecated since 1.9
  includes/export/SMW_ExportController.php
  src/GlobalFunctions.php
  tests/phpunit/Unit/GlobalFunctionsTest.php
  tests/phpunit/Unit/NamespaceExaminerTest.php
Labels: code quality

#3419 [SMWSearch] Support completion search (in:, has:, phrase: prefix)
  DefaultSettings.php
  data/elastic/default-profile.json
  src/Elastic/QueryEngine/QueryEngine.php
  src/MediaWiki/Search/QueryBuilder.php
  src/MediaWiki/Search/Search.php
  src/MediaWiki/Search/SearchResultSet.php
  src/Query/Parser/TermParser.php
  tests/phpunit/Unit/MediaWiki/Search/SearchResultSetTest.php
  tests/phpunit/Unit/MediaWiki/Search/SearchTest.php
  tests/phpunit/Unit/Query/Parser/TermParserTest.php
Labels: feature

#3415 Special:Ask add basic compact view, refs 3180
  i18n/en.json
  res/smw/ext.smw.css
  res/smw/ext.smw.page.css
  res/smw/special/ext.smw.special.ask.css
  res/smw/special/ext.smw.special.ask.js
  res/smw/suggester/ext.smw.suggester.js
  src/MediaWiki/Hooks/GetPreferences.php
  src/MediaWiki/Specials/Ask/DownloadLinksWidget.php
  src/MediaWiki/Specials/Ask/LinksWidget.php
  src/MediaWiki/Specials/Ask/NavigationLinksWidget.php
  src/MediaWiki/Specials/Ask/QueryInputWidget.php
  src/MediaWiki/Specials/Ask/UrlArgs.php
  src/MediaWiki/Specials/SpecialAsk.php
  src/Page/ListPager.php
  src/Utils/HtmlTabs.php
  tests/phpunit/Integration/SpecialAskTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Ask/DownloadLinksWidgetTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Ask/NavigationLinksWidgetTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Ask/QueryInputWidgetTest.php
  tests/phpunit/Unit/Utils/HtmlTabsTest.php
Labels: feature, wikidocu missing

#3429 Special:Ask support different form submit methods
  DefaultSettings.php
  includes/Settings.php
  src/Defines.php
  src/MediaWiki/Specials/SpecialAsk.php
  src/Options.php
  tests/phpunit/Integration/SpecialAskTest.php
Labels: enhancement, wikidocu missing

#3438 Add deprecation notice section
  includes/Settings.php
  src/MediaWiki/Specials/Admin/DeprecationNoticeTaskHandler.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/DeprecationNoticeTaskHandlerTest.php
Labels: enhancement, wikidocu missing

#3439 Special:Ask move form build to HtmlForm
  DefaultSettings.php
  res/smw/special/ext.smw.special.ask.css
  src/MediaWiki/Specials/Ask/HtmlForm.php
  src/MediaWiki/Specials/Ask/NavigationLinksWidget.php
  src/MediaWiki/Specials/SpecialAsk.php
  tests/phpunit/Unit/MediaWiki/Specials/Ask/HtmlFormTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Ask/NavigationLinksWidgetTest.php
Labels: code quality

#3441 rebuildData.php add "--revision-mode", refs 1698, 3390
  includes/storage/SQLStore/SMW_Sql3SmwIds.php
  maintenance/rebuildData.php
  src/Maintenance/DataRebuilder.php
  src/SQLStore/EntityRebuildDispatcher.php
  tests/phpunit/Integration/JSONScript/TestCases/s-0006.json
  tests/phpunit/Unit/SQLStore/EntityRebuildDispatcherTest.php
  tests/phpunit/includes/storage/sqlstore/SQLStoreSmwIdsTest.php
Labels: enhancement

#3442 Tidy (TitleFactory)
  src/ApplicationFactory.php
  src/Maintenance/DataRebuilder.php
  src/Maintenance/DistinctEntityDataRebuilder.php
  src/Maintenance/MaintenanceFactory.php
  src/MediaWiki/Api/Browse.php
  src/MediaWiki/Api/Browse/ArticleAugmentor.php
  src/MediaWiki/Api/Browse/SubjectLookup.php
  src/MediaWiki/Api/BrowseBySubject.php
  src/MediaWiki/TitleCreator.php
  src/MediaWiki/TitleFactory.php
  src/SQLStore/EntityRebuildDispatcher.php
  src/SQLStore/SQLStoreFactory.php
  src/Services/SharedServicesContainer.php
  tests/phpunit/Unit/ApplicationFactoryTest.php
  tests/phpunit/Unit/Maintenance/DataRebuilderTest.php
  tests/phpunit/Unit/Maintenance/DistinctEntityDataRebuilderTest.php
  tests/phpunit/Unit/MediaWiki/Api/Browse/ArticleAugmentorTest.php
  tests/phpunit/Unit/MediaWiki/TitleCreatorTest.php
  tests/phpunit/Unit/MediaWiki/TitleFactoryTest.php
  tests/phpunit/Unit/SQLStore/EntityRebuildDispatcherTest.php
Labels: code quality

#3474 Consolidate factbox setting `smwgFactboxFeatures`, refs 2798
  DefaultSettings.php
  includes/Settings.php
  src/CacheFactory.php
  src/Defines.php
  src/EventListenerRegistry.php
  src/Factbox/CachedFactbox.php
  src/Factbox/Factbox.php
  src/Factbox/FactboxFactory.php
  src/MediaWiki/Hooks/ArticlePurge.php
  src/MediaWiki/Hooks/OutputPageParserOutput.php
  tests/phpunit/Integration/SemanticMediaWikiProvidedHookInterfaceIntegrationTest.php
  tests/phpunit/Unit/CacheFactoryTest.php
  tests/phpunit/Unit/Factbox/CachedFactboxTest.php
  tests/phpunit/Unit/Factbox/FactboxFactoryTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/ArticlePurgeTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/OutputPageParserOutputTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/SkinAfterContentTest.php
Labels: wikidocu missing
