Repository SemanticMediaWiki/SemanticMediaWiki, pull requests merged in 2018-08, with the labels that each got.

#3285 Special:Browse to use `smwbrowse`, deprecate `BrowseBySubject` API, refs 2696
  i18n/en.json
  res/smw/special/ext.smw.special.browse.css
  res/smw/special/ext.smw.special.browse.js
  src/Exception/ParameterNotFoundException.php
  src/Exception/RedirectTargetUnresolvableException.php
  src/MediaWiki/Api/Browse.php
  src/MediaWiki/Api/Browse/SubjectLookup.php
  src/MediaWiki/Api/BrowseByProperty.php
  src/MediaWiki/Api/BrowseBySubject.php
  src/MediaWiki/Specials/Browse/FieldBuilder.php
  src/MediaWiki/Specials/Browse/HtmlBuilder.php
  src/MediaWiki/Specials/SpecialBrowse.php
  tests/phpunit/Integration/JSONScript/Fixtures/res.a-0001.7.txt
  tests/phpunit/Integration/JSONScript/Fixtures/res.a-0001.8.txt
  tests/phpunit/Integration/JSONScript/TestCases/a-0001.json
  tests/phpunit/Unit/Exception/ParameterNotFoundExceptionTest.php
  tests/phpunit/Unit/Exception/RedirectTargetUnresolvableExceptionTest.php
  tests/phpunit/Unit/MediaWiki/Api/Browse/SubjectLookupTest.php
  tests/phpunit/Unit/MediaWiki/Api/BrowseTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Browse/FieldBuilderTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Browse/HtmlBuilderTest.php
  tests/phpunit/Unit/MediaWiki/Specials/SpecialBrowseTest.php
Labels: enhancement

#3286 Special:Browse, Special:PageProperty limit value pool, refs 2930
  DefaultSettings.php
  includes/storage/SQLStore/SMW_SQLStore3_Readers.php
  src/EntityLookup.php
  src/MediaWiki/Specials/Browse/HtmlBuilder.php
  src/MediaWiki/Specials/SpecialBrowse.php
  src/MediaWiki/Specials/SpecialPageProperty.php
  src/SQLStore/EntityStore/CachingSemanticDataLookup.php
  src/SQLStore/RequestOptionsProc.php
  tests/phpunit/Integration/JSONScript/TestCases/s-0028.json
  tests/phpunit/Unit/MediaWiki/Specials/SpecialBrowseTest.php
Labels: enhancement, performance, wikidocu missing

#3289 Combine different value lists, support JSON, refs 2295
  src/DataValues/AllowsListValue.php
  src/DataValues/ValueParsers/AllowsListValueParser.php
  src/DataValues/ValueValidators/AllowsListConstraintValueValidator.php
  tests/phpunit/Integration/JSONScript/Fixtures/p-0502-other-license.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0502.json
  tests/phpunit/Unit/DataValues/ValueParsers/AllowsListValueParserTest.php
  tests/phpunit/Unit/DataValues/ValueValidators/AllowsListConstraintValueValidatorTest.php
Labels: enhancement

#3292 `Allows value` to support bounded intervals, ranges for number, quantity type
  src/DataValues/ValueValidators/AllowsListConstraintValueValidator.php
  src/Message.php
  tests/phpunit/Integration/JSONScript/TestCases/p-0460.json
  tests/phpunit/Unit/DataValues/ValueValidators/AllowsListConstraintValueValidatorTest.php
Labels: feature

#3293 Add tanslation page annotation, refs 2300
  DefaultSettings.php
  i18n/extra/en.json
  src/DataItemFactory.php
  src/MediaWiki/Hooks/ParserAfterTidy.php
  src/PropertyAnnotatorFactory.php
  src/PropertyAnnotators/TranslationPropertyAnnotator.php
  src/TypesRegistry.php
  tests/phpunit/Unit/DataItemFactoryTest.php
  tests/phpunit/Unit/PropertyAnnotatorFactoryTest.php
  tests/phpunit/Unit/PropertyAnnotators/TranslationPropertyAnnotatorTest.php
Labels: feature

#3308 [UI] Use tabs on property, concept page
  DefaultSettings.php
  i18n/en.json
  res/Resources.php
  res/smw/ext.smw.page.css
  res/smw/ext.smw.tabs.css
  res/smw/util/smw.property.page.js
  src/Page/ConceptPage.php
  src/Page/ListBuilder/ListBuilder.php
  src/Page/ListBuilder/ValueListBuilder.php
  src/Page/ListPager.php
  src/Page/PropertyPage.php
  src/Utils/HtmlTabs.php
  tests/phpunit/Unit/Utils/HtmlTabsTest.php
Labels: wikidocu missing

#3307 Switch to smwgMainCacheType
  DefaultSettings.php
  SemanticMediaWiki.php
  includes/Settings.php
  src/ApplicationFactory.php
  src/Factbox/FactboxFactory.php
  tests/phpunit/Integration/MediaWiki/Hooks/FileUploadIntegrationTest.php
  tests/phpunit/Integration/MediaWiki/Hooks/ParserFirstCallInitIntegrationTest.php
  tests/phpunit/Integration/MediaWiki/MediaWikiIntegrationForRegisteredHookTest.php
  tests/phpunit/Integration/Parser/InTextAnnotationParserTemplateTransclusionTest.php
  tests/phpunit/Integration/RdfFileResourceTest.php
  tests/phpunit/Unit/Factbox/CachedFactboxTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/ArticlePurgeTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/FileUploadTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/OutputPageParserOutputTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/ParserAfterTidyTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/SkinAfterContentTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/TitleMoveCompleteTest.php
  tests/phpunit/Unit/MediaWiki/Jobs/UpdateDispatcherJobTest.php
  tests/phpunit/Unit/MediaWiki/Jobs/UpdateJobTest.php
  tests/phpunit/Unit/PropertyChangePropagationNotifierTest.php
  tests/phpunit/Unit/SQLStore/EntityRebuildDispatcherTest.php
  tests/phpunit/includes/SetupTest.php
Labels: wikidocu missing

#3318 Add smwgPostEditUpdate, refs 3310
  DefaultSettings.php
  i18n/en.json
  includes/Settings.php
  res/smw/util/ext.smw.util.postproc.js
  src/MediaWiki/Api/Task.php
  src/MediaWiki/Jobs/ParserCachePurgeJob.php
  src/MediaWiki/Jobs/UpdateJob.php
  src/PostProcHandler.php
  src/SQLStore/QueryDependency/DependencyLinksUpdateJournal.php
  src/Services/SharedServicesContainer.php
  tests/phpunit/Unit/MediaWiki/Api/TaskTest.php
  tests/phpunit/Unit/PostProcHandlerTest.php
  tests/phpunit/Unit/SQLStore/QueryDependency/DependencyLinksUpdateJournalTest.php
Labels: wikidocu missing

#3315 Consolidate sparql endpoint setting `smwgSparqlEndpoint`
  DefaultSettings.php
  includes/Settings.php
  src/SPARQLStore/RepositoryConnectionProvider.php
  src/SPARQLStore/RepositoryConnectors/VirtuosoRepositoryConnector.php
  src/SPARQLStore/SPARQLStoreFactory.php
  tests/travis/update-configuration-settings.sh
Labels: wikidocu missing

#3339 Add support for uniqueness validation in records/references, refs 1463
  i18n/en.json
  includes/datavalues/SMW_DV_Record.php
  src/DataValues/ValueValidators/UniquenessConstraintValueValidator.php
  src/SQLStore/EntityValueUniquenessConstraintChecker.php
  src/SQLStore/SQLStoreFactory.php
  src/Services/DataValueServices.php
  tests/phpunit/Integration/JSONScript/TestCases/p-0419.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0421.json
  tests/phpunit/Unit/DataValues/ValueValidators/UniquenessConstraintValueValidatorTest.php
  tests/phpunit/Unit/SQLStore/EntityValueUniquenessConstraintCheckerTest.php
  tests/phpunit/Unit/SQLStore/SQLStoreFactoryTest.php
  tests/phpunit/Unit/Services/DataValueServicesContainerBuildTest.php
Labels: enhancement

#3348 [CI] Drop hhvm-3.18/master test run, refs 2688
  .travis.yml
Labels: infrastructure

#3353 [DB] SQLite use temporary table to drop field
  src/SQLStore/TableBuilder/SQLiteTableBuilder.php
Labels: rdbms-sqlite

#3357 [ES] Add cjk.best.effort.proximity.match
  DefaultSettings.php
  src/Elastic/QueryEngine/Condition.php
  src/Elastic/QueryEngine/DescriptionInterpreters/SomeValueInterpreter.php
  src/Elastic/QueryEngine/DescriptionInterpreters/ValueDescriptionInterpreter.php
  src/Elastic/QueryEngine/QueryEngine.php
  src/MediaWiki/Search/SearchResultSet.php
  src/Utils/CharExaminer.php
  tests/phpunit/Integration/JSONScript/TestCases/q-1206.json
  tests/phpunit/Unit/Elastic/QueryEngine/DescriptionInterpreters/SomeValueInterpreterTest.php
  tests/phpunit/Unit/Elastic/QueryEngine/DescriptionInterpreters/ValueDescriptionInterpreterTest.php
  tests/phpunit/Unit/Utils/CharExaminerTest.php
Labels: feature

#3366 Stop using deprecated alias in SMWDataValue
  includes/datavalues/SMW_DataValue.php
Labels: code quality

#3367 Remove weird code in clearSubSemanticData
  includes/SemanticData.php
Labels: code quality

#3368 Remove unused private method
  includes/SemanticData.php
  includes/Settings.php
Labels: code quality

#3369 Do not return void methods
  includes/datavalues/SMW_DV_URI.php
  includes/datavalues/SMW_DV_WikiPage.php
Labels: code quality

#3370 Stop using deprecated method in Settings
  includes/Settings.php
Labels: code quality

#3364 Remove long deprecated static functions
  includes/datavalues/SMW_DV_WikiPage.php
Labels: code quality

#3363 Remove deprecated m_params field
  src/Query/ResultPrinters/ResultPrinter.php
Labels: code quality
