Repository SemanticMediaWiki/SemanticMediaWiki, pull requests merged in 2020-02, with the labels that each got.

#4493 Check and add `smw-property-predefined-...` descriptions
  i18n/en.json
  tests/phpunit/Integration/System/I18nMsgDescriptionPredefinedPropertyTest.php
Labels: code quality

#4496 [ES] Refactor `FileIndexer`
  src/Elastic/ElasticFactory.php
  src/Elastic/ElasticStore.php
  src/Elastic/Indexer/Attachment/AttachmentAnnotator.php
  src/Elastic/Indexer/Attachment/FileAttachment.php
  src/Elastic/Indexer/Attachment/FileHandler.php
  src/Elastic/Indexer/Attachment/ScopeMemoryLimiter.php
  src/Elastic/Indexer/FileIndexer.php
  src/Elastic/Indexer/Indexer.php
  src/Elastic/Indexer/Rebuilder/Rebuilder.php
  src/Elastic/Jobs/FileIngestJob.php
  src/MediaWiki/FileRepoFinder.php
  src/MediaWiki/HookDispatcher.php
  src/MediaWiki/Hooks/FileUpload.php
  src/MediaWiki/Job.php
  src/MediaWiki/RevisionGuard.php
  src/Services/mediawiki.php
  src/Setup.php
  tests/phpunit/Integration/MediaWiki/HookDispatcherTest.php
  tests/phpunit/Unit/Elastic/ElasticFactoryTest.php
  tests/phpunit/Unit/Elastic/ElasticStoreTest.php
  tests/phpunit/Unit/Elastic/Indexer/Attachment/AttachmentAnnotatorTest.php
  tests/phpunit/Unit/Elastic/Indexer/Attachment/FileAttachmentTest.php
  tests/phpunit/Unit/Elastic/Indexer/Attachment/FileHandlerTest.php
  tests/phpunit/Unit/Elastic/Indexer/Attachment/ScopeMemoryLimiterTest.php
  tests/phpunit/Unit/Elastic/Indexer/FileIndexerTest.php
  tests/phpunit/Unit/Elastic/Indexer/Rebuilder/RebuilderTest.php
  tests/phpunit/Unit/Elastic/Jobs/FileIngestJobTest.php
  tests/phpunit/Unit/MediaWiki/FileRepoFinderTest.php
  tests/phpunit/Unit/MediaWiki/RevisionGuardTest.php
  tests/phpunit/Utils/MwHooksHandler.php
Labels: code quality

#4498 [ES] Refactor `Indexer`, add `Document` and `DocumentCreator`
  DefaultSettings.php
  data/elastic/default-profile.json
  maintenance/rebuildElasticIndex.php
  src/Elastic/ElasticFactory.php
  src/Elastic/ElasticStore.php
  src/Elastic/Indexer/Attachment/FileAttachment.php
  src/Elastic/Indexer/Bulk.php
  src/Elastic/Indexer/Document.php
  src/Elastic/Indexer/DocumentCreator.php
  src/Elastic/Indexer/Indexer.php
  src/Elastic/Indexer/Rebuilder/Rebuilder.php
  src/Elastic/Indexer/TextSanitizer.php
  src/Elastic/Installer.php
  src/Elastic/Jobs/IndexerRecoveryJob.php
  src/SQLStore/EntityStore/EntityIdManager.php
  src/SQLStore/SQLStoreFactory.php
  src/Services/SharedServicesContainer.php
  src/Setup.php
  tests/phpunit/Integration/Elastic/DefaultConfigTest.php
  tests/phpunit/Unit/Elastic/ElasticFactoryTest.php
  tests/phpunit/Unit/Elastic/ElasticStoreTest.php
  tests/phpunit/Unit/Elastic/Indexer/Attachment/FileAttachmentTest.php
  tests/phpunit/Unit/Elastic/Indexer/BulkTest.php
  tests/phpunit/Unit/Elastic/Indexer/DocumentCreatorTest.php
  tests/phpunit/Unit/Elastic/Indexer/DocumentTest.php
  tests/phpunit/Unit/Elastic/Indexer/IndexerRecoveryJobTest.php
  tests/phpunit/Unit/Elastic/Indexer/IndexerTest.php
  tests/phpunit/Unit/Elastic/Indexer/Rebuilder/RebuilderTest.php
  tests/phpunit/Unit/Elastic/Indexer/TextSanitizerTest.php
  tests/phpunit/Unit/Elastic/InstallerTest.php
  tests/phpunit/Unit/Elastic/Jobs/IndexerRecoveryJobTest.php
Labels: code quality

#4504 [ES] Add `ReplicationError`
  data/template/elastic/indexer/checkreplication.compare.list.ms
  i18n/en.json
  maintenance/rebuildElasticMissingDocuments.php
  res/Resources.php
  res/smw/util/smw.check.replication.css
  src/Elastic/Indexer/Replication/CheckReplicationTask.php
  src/Elastic/Indexer/Replication/DocumentReplicationExaminer.php
  src/Elastic/Indexer/Replication/ReplicationError.php
  src/Elastic/Indexer/Replication/ReplicationStatus.php
  tests/phpunit/Unit/Elastic/Indexer/Replication/CheckReplicationTaskTest.php
  tests/phpunit/Unit/Elastic/Indexer/Replication/DocumentReplicationExaminerTest.php
  tests/phpunit/Unit/Elastic/Indexer/Replication/ReplicationErrorTest.php
  tests/phpunit/Unit/Elastic/Indexer/Replication/ReplicationStatusTest.php
Labels: enhancement

#4516 Fix external identifier formatting in reference, refs 2986
  src/DataValues/ValueFormatters/ReferenceValueFormatter.php
  tests/phpunit/Integration/JSONScript/TestCases/p-0916.json
Labels: bug

#4529 [ES] Fix progress display in `rebuildElasticIndex`
  maintenance/rebuildElasticIndex.php
Labels: code quality

#4550 Check for `false`, refs 4308
  src/MediaWiki/Page/PropertyPage.php
Labels: code quality

#4571 Optimize `MonolingualTextLookup` to avoid ID lookup, refs 3870
  includes/dataitems/SMW_DI_WikiPage.php
  src/DataValues/MonolingualTextValue.php
  src/Defines.php
  src/SQLStore/EntityStore/EntityIdFinder.php
  src/SQLStore/Lookup/MonolingualTextLookup.php
  src/SQLStore/TableBuilder/Examiner/PredefinedProperties.php
  tests/phpunit/Unit/SQLStore/Lookup/MonolingualTextLookupTest.php
  tests/phpunit/includes/dataitems/DIWikiPageTest.php
Labels: enhancement

#4572 Optimize chain lookup in prefetch mode, refs 3722
  src/Query/Result/FieldItemFinder.php
  src/Query/Result/ItemFetcher.php
  src/SQLStore/EntityStore/PrefetchCache.php
  src/SQLStore/EntityStore/SemanticDataLookup.php
  tests/phpunit/Integration/JSONScript/TestCases/p-0467.json
Labels: enhancement

#4586 Add max-width, theme parameter to #info
  includes/Highlighter.php
  res/smw/util/smw.tippy.css
  res/smw/util/smw.tippy.js
  src/ParserFunctions/InfoParserFunction.php
  tests/phpunit/Integration/JSONScript/TestCases/p-0106.json
  tests/phpunit/Integration/JSONScript/TestCases/p-0109.json
  tests/phpunit/Unit/ParserFunctions/InfoParserFunctionTest.php
Labels: enhancement

#4588 Remove unused newConstraintOptions
  src/ConstraintFactory.php
  tests/phpunit/Unit/ConstraintFactoryTest.php
Labels: code quality

#4589 Fix "smwtable-clean" class being broad by default
  res/smw/ext.smw.css
Labels: code quality
