Repository SemanticMediaWiki/SemanticMediaWiki, pull requests merged in 2020-01, with the labels that each got.

#4380 Static analysis fixes in CacheFactory
  src/CacheFactory.php
Labels: code quality

#4398 Identify core, custom table
  src/SQLStore/PropertyTableDefinition.php
  src/SQLStore/PropertyTableDefinitionBuilder.php
  src/SQLStore/TableBuilder/Table.php
  src/SQLStore/TableBuilder/TableSchemaManager.php
  tests/phpunit/Unit/SQLStore/PropertyTableDefinitionBuilderTest.php
  tests/phpunit/Unit/SQLStore/PropertyTableDefinitionTest.php
  tests/phpunit/Unit/SQLStore/TableBuilder/TableTest.php
Labels: enhancement

#4399 Invalidate `PropertySpecificationLookupCache` on update event
  src/DataUpdater.php
  src/EntityCache.php
  src/EventListenerRegistry.php
  src/Events/InvalidatePropertySpecificationLookupCacheEventListener.php
  src/MediaWiki/Jobs/ChangePropagationDispatchJob.php
  src/Property/SpecificationLookup.php
  src/Services/ServicesFactory.php
  src/Services/events.php
  tests/phpunit/Unit/DataUpdaterTest.php
  tests/phpunit/Unit/EntityCacheTest.php
  tests/phpunit/Unit/Events/InvalidatePropertySpecificationLookupCacheEventListenerTest.php
  tests/phpunit/Unit/Property/SpecificationLookupTest.php
  tests/phpunit/Unit/Services/EventsServicesContainerBuildTest.php
Labels: enhancement

#4400 Check for `wgFullyInitialised`, `MW_NO_SESSION`
  src/MediaWiki/Hooks.php
  src/MediaWiki/Hooks/LinksUpdateConstructed.php
  src/MediaWiki/Hooks/ParserAfterTidy.php
  src/Site.php
  tests/phpunit/Unit/MediaWiki/Hooks/LinksUpdateConstructedTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/ParserAfterTidyTest.php
  tests/phpunit/Unit/SiteTest.php
Labels: enhancement

#4403 Improve cli output (Install, setupStore.php)
  maintenance/setupStore.php
  src/Defines.php
  src/Elastic/ElasticStore.php
  src/MediaWiki/Hooks/ExtensionSchemaUpdates.php
  src/SQLStore/Installer.php
  src/SQLStore/TableBuilder/Examiner/HashField.php
  src/SQLStore/TableBuilder/Examiner/IdBorder.php
  src/SQLStore/TableBuilder/MySQLTableBuilder.php
  src/SQLStore/TableBuilder/TableBuilder.php
  src/SetupFile.php
  src/Utils/CliMsgFormatter.php
  src/Utils/Timer.php
  tests/phpunit/Integration/Maintenance/SetupStoreMaintenanceTest.php
  tests/phpunit/Integration/SQLStore/TableBuilder/TableBuilderIntegrationTest.php
  tests/phpunit/Unit/Elastic/ElasticStoreTest.php
  tests/phpunit/Unit/SQLStore/TableBuilder/Examiner/IdBorderTest.php
  tests/phpunit/Unit/SQLStore/TableBuilder/MySQLTableBuilderTest.php
  tests/phpunit/Unit/Utils/CliMsgFormatterTest.php
Labels: enhancement

#4404 Add `seld/jsonlint` and `JSONParseException`
  composer.json
  src/Exception/JSONFileParseException.php
  src/Exception/JSONParseException.php
  tests/phpunit/Fixtures/Exception/invalid.trailing.comma.json
  tests/phpunit/Unit/Exception/JSONFileParseExceptionTest.php
  tests/phpunit/Unit/Exception/JSONParseExceptionTest.php
Labels: enhancement

#4410 Tidy (Settings)
  includes/Settings.php
  tests/phpunit/includes/SettingsTest.php
Labels: code quality

#4409 Add max depth to `FileFetcher`, 3582
  src/Utils/FileFetcher.php
  tests/phpunit/Fixtures/Utils/subDir/bbb.json
  tests/phpunit/Integration/Utils/FileFetcherRoundTripTest.php
Labels: code quality

#4411 CompartmentIterator to handle associative array, refs 4279
  src/Iterators/DotSeekableIteratorTrait.php
  src/Iterators/SeekableIteratorTrait.php
  src/Schema/Compartment.php
  src/Schema/CompartmentIterator.php
  src/Schema/SchemaList.php
  tests/phpunit/Fixtures/Schema/fake_iterator_schema.json
  tests/phpunit/Integration/Schema/CompartmentIteratorSchemaListTest.php
  tests/phpunit/Unit/Iterators/DotSeekableIteratorTraitTest.php
  tests/phpunit/Unit/Iterators/SeekableIteratorTraitTest.php
  tests/phpunit/Unit/Schema/CompartmentIteratorTest.php
  tests/phpunit/Unit/Schema/CompartmentTest.php
  tests/phpunit/Unit/Schema/SchemaListTest.php
Labels: enhancement

#4415 [ES] Tidy (Config)
  DefaultSettings.php
  data/elastic/default-profile.json
  src/Elastic/Admin/ElasticClientTaskHandler.php
  src/Elastic/Config.php
  src/Elastic/Connection/Client.php
  src/Elastic/Connection/ConnectionProvider.php
  src/Elastic/Connection/DummyClient.php
  src/Elastic/ElasticFactory.php
  src/Elastic/ElasticStore.php
  tests/phpunit/Integration/Elastic/DefaultConfigTest.php
  tests/phpunit/Unit/Elastic/ConfigTest.php
  tests/phpunit/Unit/Elastic/Connection/ClientTest.php
  tests/phpunit/Unit/Elastic/Connection/ConnectionProviderTest.php
Labels: code quality

#4417 Use top navigation in JSONView, refs 3673
  res/Resources.php
  res/smw/content/smw.schema.css
  res/smw/smw.jsonview.css
  res/smw/smw.jsonview.js
  res/smw/special/ext.smw.special.css
  src/MediaWiki/Content/HtmlBuilder.php
  src/MediaWiki/Specials/Admin/Supplement/ConfigurationListTaskHandler.php
  src/MediaWiki/Specials/Admin/Supplement/TableStatisticsTaskHandler.php
Labels: enhancement

#4422 Add search field to JSONView, refs 3673, 4417
  i18n/en.json
  res/Resources.php
  res/jquery/jquery.mark.js
  res/smw/ext.smw.skin.css
  res/smw/smw.jsonview.css
  res/smw/smw.jsonview.js
Labels: enhancement

#4418 Isolate `Settings` legacy mapping
  includes/Settings.php
  src/ConfigLegacyTrait.php
  tests/phpunit/includes/SettingsTest.php
Labels: code quality

#4429 Add `SetupFile::setLatestVersion`
  maintenance/populateHashField.php
  maintenance/rebuildElasticIndex.php
  src/Elastic/ElasticStore.php
  src/SQLStore/Installer.php
  src/SetupFile.php
  tests/phpunit/Unit/Elastic/ElasticStoreTest.php
  tests/phpunit/Unit/SQLStore/InstallerTest.php
  tests/phpunit/Unit/SetupFileTest.php
Labels: enhancement

#4433 Cache schema list lookup by type
  src/SQLStore/SQLStoreFactory.php
  src/Schema/SchemaFactory.php
  src/Schema/SchemaFinder.php
  tests/phpunit/Unit/Listener/ChangeListener/ChangeListeners/PropertyChangeListenerTest.php
  tests/phpunit/Unit/SQLStore/SQLStoreFactoryTest.php
  tests/phpunit/Unit/Schema/SchemaFinderTest.php
Labels: enhancement

#4435 Add bulk load, refs 3774
  src/Utils/TemplateEngine.php
  tests/phpunit/Fixtures/readable.file
  tests/phpunit/Unit/Utils/TemplateEngineTest.php
Labels: enhancement

#4438 Different approach for extension check, refs 4119, 4190
  DefaultSettings.php
  SemanticMediaWiki.php
  data/template/setupcheck/setupcheck.errorbox.ms
  data/template/setupcheck/setupcheck.json
  data/template/setupcheck/setupcheck.ms
  data/template/setupcheck/setupcheck.paragraph.ms
  data/template/setupcheck/setupcheck.progress.ms
  data/template/setupcheck/setupcheck.section.ms
  data/template/setupcheck/setupcheck.version.ms
  i18n/local/setupcheck.i18n.json
  src/Connection/ConnectionManager.php
  src/GlobalFunctions.php
  src/Setup.php
  src/SetupCheck.php
  src/UncaughtExceptionHandler.php
  tests/phpunit/Fixtures/invalid.json
  tests/phpunit/Unit/SetupCheckTest.php
  tests/phpunit/Unit/SetupTest.php
  tests/phpunit/Unit/UncaughtExceptionHandlerTest.php
Labels: enhancement, wikidocu missing

#4436 Fix @annotation behavior when used with Page Forms
  src/MediaWiki/Hooks/OutputPageParserOutput.php
Labels: enhancement

#4439 Add ERROR_DB_REQUIREMENT_INCOMPATIBLE, refs 4438
  data/template/setupcheck/setupcheck.db.requirement.ms
  data/template/setupcheck/setupcheck.json
  i18n/local/setupcheck.i18n.json
  src/SetupCheck.php
  src/SetupFile.php
  tests/phpunit/Unit/SetupFileTest.php
Labels: enhancement

#4460 Removed broken & unused imports
  src/MediaWiki/Hooks/OutputPageParserOutput.php
Labels: code quality

#4450 Add `SemanticData::isStub`
  includes/SemanticData.php
  src/SQLStore/EntityStore/StubSemanticData.php
Labels: enhancement

#4451 [CI] SQLStoreFactory coverage
  tests/phpunit/Unit/SQLStore/SQLStoreFactoryTest.php
Labels: code quality

#4452 Special:Browse use structured array instead of hash
  res/smw/special/ext.smw.special.browse.js
  src/MediaWiki/Specials/Browse/HtmlBuilder.php
  tests/phpunit/Unit/MediaWiki/Specials/SpecialBrowseTest.php
Labels: enhancement

#4454 Optimize `exclude_limit`, refs 4063, 4064
  src/SQLStore/EntityStore/PropertySubjectsLookup.php
  src/SQLStore/EntityStore/ResultLimiter.php
  src/SQLStore/EntityStore/SemanticDataLookup.php
  tests/phpunit/Integration/JSONScript/TestCases/q-0626.json
  tests/phpunit/Unit/SQLStore/EntityStore/ResultLimiterTest.php
Labels: enhancement

#4456 Add HookListener
  src/MediaWiki/HookListener.php
  src/MediaWiki/Hooks.php
  src/MediaWiki/Hooks/ApiModuleManager.php
  src/MediaWiki/Hooks/ArticleDelete.php
  src/MediaWiki/Hooks/ArticleFromTitle.php
  src/MediaWiki/Hooks/ArticleProtectComplete.php
  src/MediaWiki/Hooks/ArticlePurge.php
  src/MediaWiki/Hooks/ArticleViewHeader.php
  src/MediaWiki/Hooks/BaseTemplateToolbox.php
  src/MediaWiki/Hooks/BeforeDisplayNoArticleText.php
  src/MediaWiki/Hooks/BeforePageDisplay.php
  src/MediaWiki/Hooks/EditPageForm.php
  src/MediaWiki/Hooks/ExtensionSchemaUpdates.php
  src/MediaWiki/Hooks/ExtensionTypes.php
  src/MediaWiki/Hooks/FileUpload.php
  src/MediaWiki/Hooks/GetPreferences.php
  src/MediaWiki/Hooks/InternalParseBeforeLinks.php
  src/MediaWiki/Hooks/LinksUpdateConstructed.php
  src/MediaWiki/Hooks/NewRevisionFromEditComplete.php
  src/MediaWiki/Hooks/OutputPageParserOutput.php
  src/MediaWiki/Hooks/ParserAfterTidy.php
  src/MediaWiki/Hooks/PersonalUrls.php
  src/MediaWiki/Hooks/RejectParserCacheValue.php
  src/MediaWiki/Hooks/ResourceLoaderGetConfigVars.php
  src/MediaWiki/Hooks/ResourceLoaderTestModules.php
  src/MediaWiki/Hooks/SkinAfterContent.php
  src/MediaWiki/Hooks/SkinTemplateNavigation.php
  src/MediaWiki/Hooks/SpecialPageList.php
  src/MediaWiki/Hooks/SpecialSearchResultsPrepend.php
  src/MediaWiki/Hooks/SpecialStatsAddExtra.php
  src/MediaWiki/Hooks/TitleIsAlwaysKnown.php
  src/MediaWiki/Hooks/TitleIsMovable.php
  src/MediaWiki/Hooks/TitleMoveComplete.php
  src/MediaWiki/Hooks/TitleQuickPermissions.php
  src/MediaWiki/Hooks/UserChange.php
  src/OptionsAwareTrait.php
  tests/phpunit/Unit/MediaWiki/Hooks/HookHandlerTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/SkinAfterContentTest.php
  tests/phpunit/Unit/MediaWiki/HooksTest.php
  tests/phpunit/Unit/OptionsAwareTraitTest.php
Labels: code quality

#4458 Add `Special:PendingTaskList`
  i18n/en.json
  i18n/extra/SemanticMediaWiki.alias.php
  maintenance/populateHashField.php
  res/smw/ext.smw.skin.css
  res/smw/ext.smw.tabs.css
  res/smw/special/ext.smw.special.css
  src/Elastic/ElasticStore.php
  src/MediaWiki/Hooks.php
  src/MediaWiki/Hooks/BeforePageDisplay.php
  src/MediaWiki/Hooks/SpecialPageList.php
  src/MediaWiki/Specials/PendingTasks/IncompleteSetupTasks.php
  src/MediaWiki/Specials/SpecialPendingTaskList.php
  src/SetupFile.php
  tests/phpunit/Unit/MediaWiki/Hooks/BeforePageDisplayTest.php
  tests/phpunit/Unit/MediaWiki/Specials/PendingTasks/IncompleteSetupTasksTest.php
  tests/phpunit/Unit/MediaWiki/Specials/SpecialPendingTaskListTest.php
Labels: enhancement, wikidocu missing

#4459 Add `ActionableTask`
  res/smw/smw.jsonview.js
  res/smw/special/ext.smw.special.admin.js
  src/Elastic/Admin/ElasticClientTaskHandler.php
  src/Elastic/Admin/IndicesInfoProvider.php
  src/Elastic/Admin/InfoProviderHandler.php
  src/Elastic/Admin/MappingsInfoProvider.php
  src/MediaWiki/Specials/Admin/ActionableTask.php
  src/MediaWiki/Specials/Admin/DeprecationNoticeTaskHandler.php
  src/MediaWiki/Specials/Admin/Maintenance/DataRefreshJobTaskHandler.php
  src/MediaWiki/Specials/Admin/Maintenance/DisposeJobTaskHandler.php
  src/MediaWiki/Specials/Admin/Maintenance/FulltextSearchTableRebuildJobTaskHandler.php
  src/MediaWiki/Specials/Admin/Maintenance/PropertyStatsRebuildJobTaskHandler.php
  src/MediaWiki/Specials/Admin/Maintenance/TableSchemaTaskHandler.php
  src/MediaWiki/Specials/Admin/MaintenanceTaskHandler.php
  src/MediaWiki/Specials/Admin/Supplement/CacheStatisticsListTaskHandler.php
  src/MediaWiki/Specials/Admin/Supplement/ConfigurationListTaskHandler.php
  src/MediaWiki/Specials/Admin/Supplement/DuplicateLookupTaskHandler.php
  src/MediaWiki/Specials/Admin/Supplement/EntityLookupTaskHandler.php
  src/MediaWiki/Specials/Admin/Supplement/OperationalStatisticsListTaskHandler.php
  src/MediaWiki/Specials/Admin/Supplement/TableStatisticsTaskHandler.php
  src/MediaWiki/Specials/Admin/SupplementTaskHandler.php
  src/MediaWiki/Specials/Admin/SupportListTaskHandler.php
  src/MediaWiki/Specials/Admin/TaskHandler.php
  src/MediaWiki/Specials/Admin/TaskHandlerFactory.php
  tests/phpunit/Unit/Elastic/Admin/ElasticClientTaskHandlerTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/Maintenance/DataRefreshJobTaskHandlerTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/MaintenanceTaskHandlerTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/Supplement/OperationalStatisticsListTaskHandlerTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/SupplementTaskHandlerTest.php
Labels: code quality

#4461 Check `Setup::MINIMUM_DB_VERSION`, refs 4439, 4438
  src/SQLStore/Installer.php
  src/SQLStore/TableBuilder/TableBuildExaminer.php
  src/Setup.php
  src/SetupCheck.php
  src/SetupFile.php
  tests/phpunit/Unit/SQLStore/InstallerTest.php
  tests/phpunit/Unit/SQLStore/TableBuilder/TableBuildExaminerTest.php
  tests/phpunit/Unit/SetupFileTest.php
Labels: enhancement

#4453 Move events to listener NS, refs 4432
  src/Listener/EventListener/EventHandler.php
  src/Listener/EventListener/EventListenerRegistry.php
  src/Listener/EventListener/EventListeners/InvalidateEntityCacheEventListener.php
  src/Listener/EventListener/EventListeners/InvalidatePropertySpecificationLookupCacheEventListener.php
  src/Listener/EventListener/EventListeners/InvalidateResultCacheEventListener.php
  src/Maintenance/DuplicateEntitiesDisposer.php
  src/MediaWiki/Hooks/ArticleDelete.php
  src/MediaWiki/Hooks/ArticlePurge.php
  src/MediaWiki/Hooks/NewRevisionFromEditComplete.php
  src/MediaWiki/Jobs/UpdateJob.php
  src/SQLStore/PropertyTableIdReferenceDisposer.php
  src/SQLStore/Rebuilder/Rebuilder.php
  src/SQLStore/SQLStoreFactory.php
  src/Services/ServicesFactory.php
  src/Services/events.php
  tests/phpunit/Integration/MediaWiki/Import/Maintenance/DumpRdfMaintenanceTest.php
  tests/phpunit/LightweightJsonTestCaseScriptRunner.php
  tests/phpunit/Unit/DataUpdaterTest.php
  tests/phpunit/Unit/Listener/EventListener/EventHandlerTest.php
  tests/phpunit/Unit/Listener/EventListener/EventListenerRegistryTest.php
  tests/phpunit/Unit/Listener/EventListener/EventListeners/InvalidateEntityCacheEventListenerTest.php
  tests/phpunit/Unit/Listener/EventListener/EventListeners/InvalidatePropertySpecificationLookupCacheEventListenerTest.php
  tests/phpunit/Unit/Listener/EventListener/EventListeners/InvalidateResultCacheEventListenerTest.php
  tests/phpunit/Unit/Maintenance/DuplicateEntitiesDisposerTest.php
  tests/phpunit/Unit/SQLStore/PropertyTableIdReferenceDisposerTest.php
  tests/phpunit/Unit/SQLStore/Rebuilder/RebuilderTest.php
  tests/phpunit/Unit/Services/EventsServicesContainerBuildTest.php
Labels: code quality

#4463 Improve cli output (purgeEntityCache), refs 4403
  maintenance/purgeEntityCache.php
  tests/phpunit/Integration/Maintenance/PurgeEntityCacheTest.php
Labels: enhancement

#4464 Improve cli output (rebuildElasticMissingDocuments), refs 4403
  maintenance/rebuildElasticMissingDocuments.php
Labels: enhancement

#4466 Add `runImport.php`
  DefaultSettings.php
  maintenance/runImport.php
  maintenance/setupStore.php
  src/Exception/JSONFileParseException.php
  src/Importer/ContentCreators/TextContentCreator.php
  src/Importer/ContentIterator.php
  src/Importer/ImportContents.php
  src/Importer/Importer.php
  src/Importer/JsonContentIterator.php
  src/Importer/JsonImportContentsFileDirReader.php
  src/MediaWiki/Hooks.php
  src/MediaWiki/Hooks/ExtensionSchemaUpdates.php
  src/SQLStore/Installer.php
  src/Services/importer.php
  src/Utils/CliMsgFormatter.php
  tests/bootstrap.php
  tests/phpunit/Fixtures/Importer/Others/InvalidJsonContent/invalid.json
  tests/phpunit/Fixtures/Importer/Others/MissingSections/error.json
  tests/phpunit/Fixtures/Importer/Others/NoImportFormat/error.json
  tests/phpunit/Fixtures/Importer/Others/ValidTextContent/content.json
  tests/phpunit/Fixtures/Importer/Others/ValidTextContent/foaf.txt
  tests/phpunit/Integration/Importer/ImporterIntegrationTest.php
  tests/phpunit/Integration/Importer/JsonFileDirReaderTest.php
  tests/phpunit/Integration/Maintenance/RunImportTest.php
  tests/phpunit/Unit/Exception/JSONFileParseExceptionTest.php
  tests/phpunit/Unit/Importer/ImporterTest.php
  tests/phpunit/Unit/Importer/JsonImportContentsFileDirReaderTest.php
  tests/phpunit/Unit/Maintenance/RunImportTest.php
Labels: enhancement

#4468 Move `Deprecation notices` to `Alerts`
  i18n/en.json
  res/smw/ext.smw.tabs.css
  res/smw/special/ext.smw.special.css
  src/MediaWiki/Specials/Admin/Alerts/DeprecationNoticeTaskHandler.php
  src/MediaWiki/Specials/Admin/Alerts/MaintenanceAlertsTaskHandler.php
  src/MediaWiki/Specials/Admin/AlertsTaskHandler.php
  src/MediaWiki/Specials/Admin/TaskHandler.php
  src/MediaWiki/Specials/Admin/TaskHandlerFactory.php
  src/MediaWiki/Specials/SpecialAdmin.php
  src/Utils/HtmlTabs.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/Alerts/DeprecationNoticeTaskHandlerTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/Alerts/MaintenanceAlertsTaskHandlerTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/AlertsTaskHandlerTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/TaskHandlerFactoryTest.php
  tests/phpunit/Unit/Utils/HtmlTabsTest.php
Labels: enhancement, wikidocu missing

#4472 Add `BATCH_ROW_SIZE` to `EntityIdDisposerJob`
  src/MediaWiki/Jobs/EntityIdDisposerJob.php
  src/SQLStore/PropertyTableIdReferenceDisposer.php
Labels: enhancement

#4476 Check `last_optimization_run`, add maintenance alert
  DefaultSettings.php
  i18n/en.json
  src/Defines.php
  src/MediaWiki/Specials/Admin/Alerts/LastOptimizationRunMaintenanceAlertTaskHandler.php
  src/MediaWiki/Specials/Admin/Alerts/MaintenanceAlertsTaskHandler.php
  src/MediaWiki/Specials/Admin/TaskHandler.php
  src/MediaWiki/Specials/Admin/TaskHandlerFactory.php
  src/SQLStore/Installer.php
  src/SetupFile.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/Alerts/LastOptimizationRunMaintenanceAlertTaskHandlerTest.php
Labels: feature

#4484 Add `disposeOutdatedEntities.php`, maintenance alert for outdated entities
  i18n/en.json
  maintenance/disposeOutdatedEntities.php
  src/Maintenance/DataRebuilder/OutdatedDisposer.php
  src/MediaWiki/Specials/Admin/Alerts/OutdatedEntitiesMaxCountThresholdMaintenanceAlertTaskHandler.php
  src/MediaWiki/Specials/Admin/TaskHandlerFactory.php
  tests/bootstrap.php
  tests/phpunit/Integration/Maintenance/DisposeOutdatedEntitiesTest.php
  tests/phpunit/Unit/Maintenance/DataRebuilder/OutdatedDisposerTest.php
  tests/phpunit/Unit/Maintenance/DisposeOutdatedEntitiesTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/Alerts/OutdatedEntitiesMaxCountThresholdMaintenanceAlertTaskHandlerTest.php
Labels: feature

#4479 Add `SchemaFilter` (`CategoryFilter`, `NamespaceFilter`), refs 4280
  src/Schema/CompartmentIterator.php
  src/Schema/Filters/CategoryFilter.php
  src/Schema/Filters/FilterTrait.php
  src/Schema/Filters/NamespaceFilter.php
  src/Schema/README.md
  src/Schema/SchemaFactory.php
  src/Schema/SchemaFilter.php
  src/Schema/SchemaFilterFactory.php
  src/Schema/SchemaList.php
  src/Schema/docs/filter.md
  tests/phpunit/Fixtures/Schema/fake_namespace_category_action_rule_schema_4.json
  tests/phpunit/Fixtures/Schema/fake_namespace_category_rule_schema_1.json
  tests/phpunit/Fixtures/Schema/fake_namespace_category_rule_schema_2.json
  tests/phpunit/Fixtures/Schema/fake_namespace_category_unnamed_rule_schema_3.json
  tests/phpunit/Integration/Schema/FilteredSchemaListTest.php
  tests/phpunit/Unit/Schema/Filters/CategoryFilterTest.php
  tests/phpunit/Unit/Schema/Filters/FilterTraitTest.php
  tests/phpunit/Unit/Schema/Filters/NamespaceFilterTest.php
  tests/phpunit/Unit/Schema/SchemaFactoryTest.php
  tests/phpunit/Unit/Schema/SchemaFilterFactoryTest.php
Labels: feature
