Repository SemanticMediaWiki/SemanticMediaWiki, pull requests merged in 2020-03, with the labels that each got.

#4613 Add `smw_countmap` field, refs 4611
  DefaultSettings.php
  i18n/en.json
  includes/SemanticData.php
  maintenance/updateEntityCountMap.php
  src/DataModel/ContainerSemanticData.php
  src/MediaWiki/Hooks/ArticleViewHeader.php
  src/Query/QueryResult.php
  src/Query/Result/FilterMap.php
  src/SQLStore/EntityStore/AuxiliaryFields.php
  src/SQLStore/EntityStore/CacheWarmer.php
  src/SQLStore/EntityStore/EntityIdManager.php
  src/SQLStore/EntityStore/FieldList.php
  src/SQLStore/EntityStore/StubSemanticData.php
  src/SQLStore/SQLStoreFactory.php
  src/SQLStore/SQLStoreUpdater.php
  src/SQLStore/TableBuilder/Examiner/CountMapField.php
  src/SQLStore/TableBuilder/TableBuildExaminer.php
  src/SQLStore/TableBuilder/TableBuildExaminerFactory.php
  src/SQLStore/TableBuilder/TableSchemaManager.php
  tests/bootstrap.php
  tests/phpunit/Integration/Maintenance/UpdateEntityCountMapTest.php
  tests/phpunit/Integration/SemanticDataCountMapIntegrationTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/ArticleViewHeaderTest.php
  tests/phpunit/Unit/MediaWiki/HooksTest.php
  tests/phpunit/Unit/Query/QueryResultTest.php
  tests/phpunit/Unit/Query/Result/FilterMapTest.php
  tests/phpunit/Unit/SQLStore/EntityStore/AuxiliaryFieldsTest.php
  tests/phpunit/Unit/SQLStore/EntityStore/CacheWarmerTest.php
  tests/phpunit/Unit/SQLStore/EntityStore/EntityIdManagerTest.php
  tests/phpunit/Unit/SQLStore/EntityStore/FieldListTest.php
  tests/phpunit/Unit/SQLStore/SQLStoreFactoryTest.php
  tests/phpunit/Unit/SQLStore/TableBuilder/TableBuildExaminerFactoryTest.php
  tests/phpunit/includes/SemanticDataTest.php
Labels: enhancement

#4622 Make list format names findable/understandable
  i18n/en.json
  i18n/qqq.json
Labels: usability

#4626 Extend use of JSONView, refs 3673
  i18n/en.json
  res/smw/special/ext.smw.special.admin.js
  res/smw/special/ext.smw.special.css
  src/Elastic/Admin/ElasticClientTaskHandler.php
  src/Elastic/Admin/IndicesInfoProvider.php
  src/Elastic/Admin/MappingsInfoProvider.php
  src/Elastic/Admin/NodesInfoProvider.php
  src/Elastic/Admin/SettingsInfoProvider.php
  src/MediaWiki/Specials/Admin/Supplement/CacheStatisticsListTaskHandler.php
  src/MediaWiki/Specials/Admin/Supplement/DuplicateLookupTaskHandler.php
  src/MediaWiki/Specials/Admin/Supplement/TableStatisticsTaskHandler.php
  src/Utils/JsonView.php
  tests/phpunit/Unit/Elastic/Admin/IndicesInfoProviderTest.php
  tests/phpunit/Unit/Elastic/Admin/MappingsInfoProviderTest.php
  tests/phpunit/Unit/Elastic/Admin/NodesInfoProviderTest.php
  tests/phpunit/Unit/Elastic/Admin/SettingsInfoProviderTest.php
  tests/phpunit/Unit/MediaWiki/Specials/Admin/Supplement/CacheStatisticsListTaskHandlerTest.php
  tests/phpunit/Unit/Utils/JsonViewTest.php
Labels: enhancement

#4627 Convert `RuntimeException` to simple error message, refs 4349
  src/SQLStore/Lookup/SingleEntityQueryLookup.php
  tests/phpunit/Integration/JSONScript/TestCases/p-0213.json
  tests/phpunit/Unit/SQLStore/Lookup/SingleEntityQueryLookupTest.php
Labels: code quality

#4630 [SPARQLStore] `SMW_SPARQL_CONNECTION_PING` to ping before update
  DefaultSettings.php
  src/Defines.php
  src/SPARQLStore/Exception/HttpEndpointConnectionException.php
  src/SPARQLStore/RepositoryClient.php
  src/SPARQLStore/RepositoryConnection.php
  src/SPARQLStore/RepositoryConnectionProvider.php
  src/SPARQLStore/RepositoryConnectors/GenericRepositoryConnector.php
  src/SPARQLStore/SPARQLStore.php
  src/SPARQLStore/SPARQLStoreFactory.php
  src/Settings.php
  tests/phpunit/Unit/SPARQLStore/RepositoryClientTest.php
  tests/phpunit/Unit/SPARQLStore/RepositoryConnectors/GenericRepositoryConnectorTest.php
  tests/phpunit/Unit/SPARQLStore/SPARQLStoreTest.php
  tests/travis/update-configuration-settings.sh
Labels: feature

#4632 Avoid "Notice: Undefined index: _CHGPRO ... SemanticData.php on line 515", refs 4613
  includes/SemanticData.php
Labels: code quality

#4633 Use `JSONParseException` instead of `json_last_error_msg`, refs 4404
  src/Exception/JSONParseException.php
  src/MediaWiki/Content/SchemaContent.php
  tests/phpunit/Unit/Exception/JSONParseExceptionTest.php
Labels: enhancement, wikidocu missing

#4634 Add HTML_TIDY to `TemplateEngine`
  src/Utils/TemplateEngine.php
  tests/phpunit/Unit/Utils/TemplateEngineTest.php
Labels: enhancement

#4635 Extend `UrlArgs`, refs 4611, 4620
  src/Utils/UrlArgs.php
  tests/phpunit/Unit/Utils/UrlArgsTest.php
Labels: enhancement

#4636 [SPARQLStore] Show detail during setup, refs 4631
  src/SPARQLStore/SPARQLStore.php
  src/SQLStore/Installer.php
Labels: enhancement

#4644 Check `justinrainbow/json-schema` is available
  i18n/en.json
  src/MediaWiki/Content/SchemaContent.php
  src/MediaWiki/Content/SchemaContentFormatter.php
  src/Utils/JsonSchemaValidator.php
  tests/phpunit/Unit/Utils/JsonSchemaValidatorTest.php
Labels: enhancement

#4649 Simplify message
  i18n/en.json
Labels: usability

#4655 Add namedargs alias to list result format
  src/Query/ResultPrinters/ListResultPrinter.php
  tests/phpunit/Integration/JSONScript/TestCases/f-0107.json
Labels: enhancement, usability

#4661 Add `CompartmentIterator::has`
  src/Schema/CompartmentIterator.php
  tests/phpunit/Unit/Schema/CompartmentIteratorTest.php
Labels: enhancement

#4664 Add namedargs alias to templatefile result format
  src/Query/ResultPrinters/TemplateFileExportPrinter.php
  tests/phpunit/Integration/JSONScript/TestCases/s-0025.json
Labels: enhancement, usability

#4665 Add namedargs alias to category result format
  src/Query/ResultPrinters/CategoryResultPrinter.php
  tests/phpunit/Integration/JSONScript/TestCases/f-0301.json
Labels: enhancement, usability

#4677 Check if `sequence_map` is available, refs 4675
  src/SQLStore/EntityStore/SemanticDataLookup.php
Labels: enhancement

#4678 Support URI group lookup, refs 4658
  src/SQLStore/Lookup/ByGroupPropertyValuesLookup.php
  tests/phpunit/Integration/SQLStore/Lookup/ByGroupPropertyValuesLookupIntegrationTest.php
Labels: enhancement
