Repository SemanticMediaWiki/SemanticMediaWiki, pull requests merged in 2020-04, with the labels that each got.

#4698 Add `PermissionExaminer`, `SMW::GroupPermissions::BeforeInitializationComplete` hook
  SemanticMediaWiki.php
  docs/technical/hooks.md
  docs/technical/hooks/hook.grouppermissions.beforeinitializationcomplete.md
  i18n/en.json
  src/Indicator/EntityExaminerIndicators/AssociatedRevisionMismatchEntityExaminerIndicatorProvider.php
  src/MediaWiki/HookDispatcher.php
  src/MediaWiki/Hooks.php
  src/MediaWiki/Hooks/GetPreferences.php
  src/MediaWiki/Hooks/OutputPageParserOutput.php
  src/MediaWiki/Hooks/PersonalUrls.php
  src/MediaWiki/IndicatorRegistry.php
  src/Permission/GroupPermissions.php
  src/Permission/PermissionAware.php
  src/Permission/PermissionExaminer.php
  src/Services/ServicesFactory.php
  src/Setup.php
  tests/phpunit/Integration/MediaWiki/HookDispatcherTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/GetPreferencesTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/OutputPageParserOutputTest.php
  tests/phpunit/Unit/MediaWiki/Hooks/PersonalUrlsTest.php
  tests/phpunit/Unit/MediaWiki/HooksTest.php
  tests/phpunit/Unit/MediaWiki/IndicatorRegistryTest.php
  tests/phpunit/Unit/Permission/GroupPermissionsTest.php
  tests/phpunit/Unit/Permission/PermissionExaminerTest.php
  tests/phpunit/Unit/SetupTest.php
  tests/phpunit/Utils/MwHooksHandler.php
Labels: enhancement, wikidocu missing

#4711 Tidy (Exporter/Serializer)
  src/Aliases.php
  src/Defines.php
  src/Exporter/Serializer/RDFXMLSerializer.php
  src/Exporter/Serializer/Serializer.php
  src/Exporter/Serializer/TurtleSerializer.php
  tests/phpunit/Unit/Exporter/Serializer/RDFXMLSerializerTest.php
  tests/phpunit/Unit/Exporter/Serializer/TurtleSerializerTest.php
Labels: code quality

#4723 Add Special:MyLanguage for better user experience
  i18n/en.json
Labels: i18n

#4731 Isolate use of `$GLOBALS['wgParserConf']`, refs 4725
  tests/phpunit/Utils/ParserFactory.php
Labels: code quality

#4730 Explicitly define `smw_id` as primary
  DefaultSettings.php
  src/SQLStore/TableBuilder/PostgresTableBuilder.php
  src/SQLStore/TableBuilder/SQLiteTableBuilder.php
  src/SQLStore/TableBuilder/TableSchemaManager.php
Labels: enhancement
