Repository SemanticMediaWiki/SemanticMediaWiki, pull requests merged in 2024-09, with the labels that each got.

#5703 Issue 5702 - clear deprecation warnings for PHP 8.1 and MW 1.39+ - null to param
  includes/Highlighter.php
  includes/SMW_Infolink.php
  src/CacheFactory.php
  src/DataValues/Number/IntlNumberFormatter.php
  src/DataValues/ValueParsers/AllowsPatternValueParser.php
  src/Localizer/Message.php
  src/MediaWiki/Connection/Query.php
  src/MediaWiki/Content/SchemaContent.php
  src/MediaWiki/Content/SchemaContentFormatter.php
  src/MediaWiki/Renderer/HtmlFormRenderer.php
  src/MediaWiki/Specials/Admin/Supplement/EntityLookupTaskHandler.php
  src/MediaWiki/Specials/Ask/NavigationLinksWidget.php
  src/MediaWiki/Specials/Ask/ParametersProcessor.php
  src/MediaWiki/Specials/Ask/QueryInputWidget.php
  src/MediaWiki/Specials/Browse/ValueFormatter.php
  src/MediaWiki/Specials/FacetedSearch/Profile.php
  src/MediaWiki/Specials/SearchByProperty/PageBuilder.php
  src/MediaWiki/StripMarkerDecoder.php
  src/MediaWiki/Template/TemplateExpander.php
  src/ParserFunctions/InfoParserFunction.php
  src/Property/SpecificationLookup.php
  src/Query/DebugFormatter.php
  src/Query/Deferred.php
  src/Query/Processor/ParamListProcessor.php
  src/Query/QueryComparator.php
  src/Query/QueryLinker.php
  src/SPARQLStore/QueryEngine/RepositoryResult.php
  src/SQLStore/Lookup/CachedListLookup.php
  src/SQLStore/PropertyTableIdReferenceFinder.php
  src/SQLStore/QueryEngine/Fulltext/SearchTableRebuilder.php
  src/SQLStore/TableBuilder/Table.php
  src/Utils/CharArmor.php
Labels: code quality, MW 1.39, PHP 8.1

#5724 Fix 2 tests failing after #5395
  tests/phpunit/NamespaceManagerTest.php
Labels: code quality

#5727 Replace deprecated alias LoadBalancer
  src/MediaWiki/Connection/LoadBalancerConnectionProvider.php
  tests/phpunit/MediaWiki/Connection/LoadBalancerConnectionProviderTest.php
  tests/phpunit/Services/MediaWikiServicesContainerBuildTest.php
Labels: MW 1.42
